### ISSUE TITLE
Research if realtime.js is a viable package name for bower/npm/etc

### ISSUE THREAD

**Issue by ianjennings** [pubnub/open-chat-framework#1]
Stephen suggests we call our realtime wrapper ```realtime.js```. It would be cool to land this name, but since it's so generic, we should see if it's taken... and it what forms.

**Comment by ianjennings** [comment]
Seems like it is! Available on bower and NPM! Google turns up nothing of value.

https://bower.io/search/
https://www.npmjs.com/package/realtime-storage
https://www.google.com/#q=%22realtime.js%22

**Comment by ianjennings** [comment]
It turns out there is a "realtimejs." 
https://github.com/matteo-ronchetti/realtimejs

Up to @stephenlb if we want to proceed.

**Comment by stephenlb** [comment]
what about one of these:

 - `open-socket`
 - `realtime-orm`
 - `openrt`
 - `open-rt`
 - `open-realtime`
