### ISSUE TITLE
Define channel hierarchy

### ISSUE THREAD

**Issue by ianjennings** [pubnub/open-chat-framework#18]
Now that we've generated some use cases, we're going to need a stronger networking pattern. This is my proposal:

* ```global```
    * Everything happens under a global channel (namespace).
    * This is where all user state is held.
    * This is where our original online list comes from
* ```global:user:username```
    * Every online user has an event feed they produce
    * Nobody else can publish to this but the user
    * PAM protected for publishing
* ```global:private:username:username```
    * Allows two (or more) users can talk to eachother
    * Also known as private chat
    * PAM protected to those users
    * usernames are sorted alpha to be predictable
* ```global:room:topic```
    * Allows any number of users to talk to each other
    * Also known as private chat

The class ```Chat``` in OCF framework should be a root class. 

* Class ```Global``` will extend ```Chat``` and include the user state.
* Class ```Feed``` will extend ```Chat``` and include the PAM protection for one user
* Class ```Private``` will extend ```Chat``` and include similar PAM protection
* Class ```Room``` will extend ```Chat``` and use strings for channel names

**Comment by ianjennings** [comment]
uses dot notation ```.```

**Comment by stephenlb** [comment]
`.`

**Comment by ianjennings** [comment]
This has been implemented.
