### ISSUE TITLE
wrap all features exposed by the pubnub js sdk in generic methods

### ISSUE THREAD

**Issue by ianjennings** [pubnub/open-chat-framework#2]
Take the JS methods exposed by pubnub.js and wrap them in generic methods. Eventually we'll map socket.io to the same methods and (#3) create a system where the user can swap pubnub.js for socket.io just by changing the config.

PubNub JS SDK Reference HERE
https://www.pubnub.com/docs/web-javascript/api-reference

**Comment by MaxPresman** [comment]
Please use V4 for this feature : )
