### ISSUE TITLE
Add persistent storage for channel info

### ISSUE THREAD

**Issue by ianjennings** [pubnub/open-chat-framework#23]
@stephenlb suggested adding information about channels to some sort of persistant store.

* Channel avatar
* Channel name
* Channel description

**Comment by ianjennings** [comment]
This can be done in a JSON file client side. Or we can store the JSON in a block and do something with rltm.js somehow. I think JSON file client side is the best.

**Comment by ianjennings** [comment]
Ask @stephenlb if this is needed for launch. I say no, or one example.

**Comment by stephenlb** [comment]
also consider channel groups.

**Comment by ianjennings** [comment]
Going to kill this and assume usage of a backend db
